// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUYU_myZhSUUs-5PKiGh9pevcjnU9VKXk',
    appId: '1:254110776760:web:542f58d9ea3bfba674634d',
    messagingSenderId: '254110776760',
    projectId: 'bajatzu-51d09',
    authDomain: 'bajatzu-51d09.firebaseapp.com',
    storageBucket: 'bajatzu-51d09.firebasestorage.app',
    measurementId: 'G-VR2E1BYXEG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCnlJMnvrElhb5b8EhGNKbun5XBL_VJk4',
    appId: '1:254110776760:android:72964265d8c9cd0874634d',
    messagingSenderId: '254110776760',
    projectId: 'bajatzu-51d09',
    storageBucket: 'bajatzu-51d09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEkJwyT5GS4fGt8ootFzY9bq-RbyYZAmQ',
    appId: '1:254110776760:ios:dd11972c01a1b4ee74634d',
    messagingSenderId: '254110776760',
    projectId: 'bajatzu-51d09',
    storageBucket: 'bajatzu-51d09.firebasestorage.app',
    iosBundleId: 'com.bajatzu.bajatzu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEkJwyT5GS4fGt8ootFzY9bq-RbyYZAmQ',
    appId: '1:254110776760:ios:dd11972c01a1b4ee74634d',
    messagingSenderId: '254110776760',
    projectId: 'bajatzu-51d09',
    storageBucket: 'bajatzu-51d09.firebasestorage.app',
    iosBundleId: 'com.bajatzu.bajatzu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUYU_myZhSUUs-5PKiGh9pevcjnU9VKXk',
    appId: '1:254110776760:web:89639dc3de9157cf74634d',
    messagingSenderId: '254110776760',
    projectId: 'bajatzu-51d09',
    authDomain: 'bajatzu-51d09.firebaseapp.com',
    storageBucket: 'bajatzu-51d09.firebasestorage.app',
    measurementId: 'G-XGLTTC54HP',
  );
}
